# Generated by Django 3.0.6 on 2020-06-24 16:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='عنوان یادداشت')),
                ('body', models.TextField(verbose_name='متن یادداشت')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.BigIntegerField(verbose_name='شماره')),
                ('image', models.ImageField(upload_to='images', verbose_name='عکس روزنامه')),
                ('file', models.FileField(upload_to='files', verbose_name='فایل پی دی اف')),
                ('pub_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspaper.Notes')),
            ],
        ),
    ]
