# Generated by Django 3.0.6 on 2020-06-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspaper',
            name='notes',
        ),
        migrations.AddField(
            model_name='newspaper',
            name='notes',
            field=models.ManyToManyField(to='newspaper.Notes'),
        ),
    ]
