# Generated by Django 3.0.6 on 2020-06-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0002_auto_20200624_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='num',
            field=models.IntegerField(verbose_name='شماره'),
        ),
    ]
